#include "displayapp/screens/OnionWatchFace.h"

#include <lvgl/lvgl.h>
#include <cstdio>

// The font is defined in a C source file; declare it with C linkage to avoid C++ name mangling.
extern "C" lv_font_t jetbrains_mono_extrabold_compressed;
// Background image descriptor generated by LVGL image converter (LVGL v8 format expected)
extern "C" const lv_img_dsc_t onion_240;

using namespace Pinetime::Applications::Screens;

OnionWatchFace::OnionWatchFace(Controllers::DateTime& dateTimeController,
                               Controllers::Settings& settingsController)
  : currentDateTime {{}} ,
    dateTimeController {dateTimeController},
    settingsController {settingsController} {

  // Create and place a full-screen background image first so other widgets render on top.
  lv_obj_t* bg = lv_img_create(lv_scr_act(), nullptr);
  lv_img_set_src(bg, &onion_240);
  // Center to cover the 240x240 screen
  lv_obj_align(bg, lv_scr_act(), LV_ALIGN_CENTER, 0, 0);
  // Ensure it stays behind labels/widgets
  lv_obj_move_background(bg);

  label_time = lv_label_create(lv_scr_act(), nullptr);
  // Use an existing large, legible font. The project includes custom JetBrains Mono fonts.
  lv_obj_set_style_local_text_font(label_time, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &jetbrains_mono_extrabold_compressed);

  // Center the time label
  lv_obj_align(label_time, lv_scr_act(), LV_ALIGN_CENTER, 0, 0);

  // Schedule periodic refresh
  taskRefresh = lv_task_create(RefreshTaskCallback, LV_DISP_DEF_REFR_PERIOD, LV_TASK_PRIO_MID, this);
  Refresh();
}

OnionWatchFace::~OnionWatchFace() {
  lv_task_del(taskRefresh);
  lv_obj_clean(lv_scr_act());
}

void OnionWatchFace::Refresh() {
  // Only update per-minute to avoid extra work
  currentDateTime = std::chrono::time_point_cast<std::chrono::minutes>(dateTimeController.CurrentDateTime());
  if (!currentDateTime.IsUpdated()) return;

  uint8_t hour = dateTimeController.Hours();
  uint8_t minute = dateTimeController.Minutes();

  if (settingsController.GetClockType() == Controllers::Settings::ClockType::H12) {
    if (hour == 0) {
      hour = 12;
    } else if (hour > 12) {
      hour -= 12;
    }
    // No AM/PM label: minimal face shows only time, centered
    lv_label_set_text_fmt(label_time, "%2d:%02d", hour, minute);
  } else {
    lv_label_set_text_fmt(label_time, "%02d:%02d", hour, minute);
  }

  // Keep it centered after text change
  lv_obj_align(label_time, lv_scr_act(), LV_ALIGN_CENTER, 0, 0);
}
